### ISSUE TITLE
각 페이지 최하단에 기여하기 페이지 링크를 추가합니다

### ISSUE THREAD

**Issue by ssinkjung** [parti-coop/toolkit#1]
### 완료조건
툴킷을 수정하거나 기여하고 싶다면 기여하기 페이지를 보세요. - 이런 문구를 각 페이지 하단에 넣습니다.

**Comment by dalikim** [comment]
자동으로 들어가는 방법은 없을까요?

**Comment by iamswain25** [comment]
> 자동으로 들어가는 방법은 없을까요?

vuepress에서 직접 지원하지는 않고, 커스터마이즈 해야합니다.
페이지 마다 따로 작업이 쉽고 편할 것 같아요.
