### ISSUE TITLE
READMEmd 툴킷 링크(url) 업데이트가 필요합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/toolkit#12]
[데모스X 운영가이드](http://demosx.org/) 데모스 운영가이드를 제외하고 아래 세 툴킷은 링크는 404로 뜨네요. 업데이트를 부탁드립니다. 

- [캠페이너 인생게임](링크 수정 필요)
- [커뮤니티 101](링크 수정 필요)
- [빠띠 타운홀 툴킷](링크 수정 필요)

**Comment by dalikim** [comment]
https://toolkit.parti.coop/

빠띠 타운홀 툴킷만 고치면 되겠는데요? @gjkimpam 님과 @iamswain25 님이 함께 수정해 보시면 어때요?

**Comment by iamswain25** [comment]
https://deploy-preview-11--goofy-bardeen-8a8fc4.netlify.com/
데모스X 추가한 새 버전에서는 수정 했습니다. 금요일에 배포할 것 같아요.

**Comment by gjkimpam** [comment]
> https://deploy-preview-11--goofy-bardeen-8a8fc4.netlify.com/
> 데모스X 추가한 새 버전에서는 수정 했습니다. 금요일에 배포할 것 같아요.

확인했습니다. 리드미.md도 말씀해주신 것 이해했어요. 작업해주셔서 고맙습니다.
