### ISSUE TITLE
기여하기 - 톤앤매너 가이드를 작성합니다

### ISSUE THREAD

**Issue by ssinkjung** [parti-coop/toolkit#2]
### 요약
툴킷을 어떤 문체, 톤, 방식으로 작성하면 되는지 가이드를 작성합니다

### 완료조건
새로운 컨트리뷰터가 가이드를 이해하고 맞춰서 작성할 수 있습니다.

**Comment by dalikim** [comment]
우선 가볍게 드는 생각은 이슈를 작성할때 "~하기"보다는 "~합니다"라고 서술로 끝나면 읽기 더 편하겠다 싶습니다. 

그리고 각 이슈의 완료 조건이 명확하면 서로 커뮤니케이션 하기 좋겠습니다. 완료 조건은 만들 때부터 기록하거나 가급적 빨리 기술을 시작하도록 유도하는 장치가 있으면 하네요. 아, 그런데 이건 톤 앤 매너랑 다른 이야기이려나요?

**Comment by ssinkjung** [comment]
@dalikim 님 좋은 제안입니다. 요약과 완료조건 2가지로 이슈 본문을 나눠보았어요. 톤앤매너와 다른 이야기지만 도움이 되었습니다. 이슈 작성의 톤앤매너에 관한 것이겠네요 :)
